# Generated by Django 5.0 on 2024-06-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_genero',
            field=models.ForeignKey(db_column='IDGenero', on_delete=django.db.models.deletion.CASCADE, to='core.genero'),
        ),
    ]
