# Generated by Django 5.0.6 on 2024-07-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_remove_usuario_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
